INST_TESTS = {
    ("rv32ui", "rv64ui"): [
        ("add", 32),
        ("addi", 32),
        ("and", 32),
        ("andi", 32),
        ("auipc", 32),
        ("beq", 32),
        ("bge", 32),
        ("bgeu", 32),
        ("blt", 32),
        ("bltu", 32),
        ("bne", 32),
        # "fence_i",
        ("jal", 32),
        ("jalr", 32),
        ("lb", 32),
        ("lbu", 32),
        ("lh", 32),
        ("lhu", 32),
        ("lui", 32),
        ("lw", 32),
        ("or", 32),
        ("ori", 32),
        ("sb", 32),
        ("sh", 32),
        ("simple", 32),
        ("sll", 32),
        ("slli", 32),
        ("slt", 32),
        ("slti", 32),
        ("sltiu", 32),
        ("sltu", 32),
        ("sra", 32),
        ("srai", 32),
        ("srl", 32),
        ("srli", 32),
        ("sub", 32),
        ("sw", 32),
        ("xor", 32),
        ("xori", 32),
    ],
    ("rv32um", "rv64um"): [
        ("div", 32),
        ("divu", 32),
        ("mul", 32),
        ("mulh", 32),
        ("mulhsu", 32),
        ("mulhu", 32),
        ("rem", 32),
        ("remu", 32),
    ],
}

def riscv_test_suite():
    all_bins = []
    for (first, second), tests in INST_TESTS.items():
        for (test, cycles) in tests:
            native.py_test(
                # tags = ["manual"],
                name = test + "_test",
                srcs = ["run_test.py"],
                main = "run_test.py",
                args = [test, str(cycles * 1024)],
                data = [
                    "//zirgen/circuit/rv32im/shared/test:riscv_test_bins",
                    ":risc0-simulate",
                ],
                size = "large",
            )
