// Copyright 2024 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Automatically generated by:
//   cargo run -p risc0-circuit-keccak -F make_control_ids --bin make_control_ids > zirgen/circuit/keccak/src/control_id.rs

use risc0_zkp::{core::digest::Digest, digest};

pub const KECCAK_CONTROL_IDS : [Digest; 11] = [

  digest!("a9838963b24ab954ab768058e886900d7f4b9f5976ad4944f95a895871eb9f45"),
  digest!("ceeffd67ad9e6428c369e90c81ce956e3eecd91f3cba493fc4c58241699d8938"),
  digest!("58c21d4a71e4ae2f0e24832e42e51625fa886c7597e21b470a721618225d784f"),
  digest!("8cc19f4fc0068c04a37f6464b3cac133246b4e0a8cdd9970ea3bda3443180c0a"),
  digest!("8bee5342674d62468e90694b30e4060bccd04c1436df8e2550f4c071a7cbd658"),
  digest!("7693471c93b1f760b113d06e8664bd0a758efd0cff9f503343e9641b96847f1d"),
  digest!("f24a0e3b8c78c760c522a4746717f4755338a2618f2c740d41f11a01b1c36735"),
  digest!("c5d4f74b4819fb5ed783a040c009e74f41b1e73b1f49fe54eb30cc20ca288420"),
  digest!("94ee132e1128c81b769a233a4b11a82c4541de2d204ef33dcbe8c93ee827f82b"),
  digest!("3d32f73befa34618a92192547fc0b466b61cea3ff63b4647e882982fd41d6e2a"),
  digest!("1d95ef135d3bd04b76c6cd351de8813c20ed3d61747cc72aa363846edf995242"),

];
pub const KECCAK_CONTROL_ROOTS : [Digest; 11] = [

  digest!("19dfd20d4654c65377da4b4c3c292e6cd1324b4e67e2f416c8f97948976ac700"),
  digest!("54954107b463312b28e870322afde41d91931c3576def24405c9f24d7728d838"),
  digest!("60430109391934267122d03753b68a441d07e333bcc3100ca8d9fc2cc28f9614"),
  digest!("0d1c65379f39216c63d4a7578a168a2354396a04cf885767cf8a9a50e2215e0c"),
  digest!("f9e0ae311ff3181febb7eb2ee171cc5fd2c42b578679f573a6dbf121fdc4a75c"),
  digest!("940f72493901294eb7494560215efa62e81b38076fed6031218f9b52e784610b"),
  digest!("69b4e8710c435b0476af6a06b57fa264a257dd6207e5ea01a0ce3a4c7990ab4a"),
  digest!("12f91b71caabab43bfe1b33ab52c3b3662bb2177dcfb3d4862cbe5223c383468"),
  digest!("3aa95b05a57fc8364f74b0399acfd63bf1a8875d34fa286107875d6a133cfa6d"),
  digest!("7ff0143d5e61302ef75ed41fc780e83ab6982133d13ea7228b80e0030b3eca71"),
  digest!("c5bf18637caa344abda65e71db51e0090f45f465668f412e08680407252d2b54"),

];
