// Copyright 2024 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Automatically generated by:
//   cargo run -p risc0-circuit-keccak -F make_control_ids --bin make_control_ids > zirgen/circuit/keccak/src/control_id.rs

use risc0_zkp::{core::digest::Digest, digest};

pub const KECCAK_CONTROL_IDS: [Digest; 11] = [
    digest!("e494d3726caf6c333bb2d075d93f1935a6a0ac2dc43ed476261577334468ab3f"),
    digest!("7afb540eafb08264bea6903ee1c7710f28374276bdbb276b5bdcee26ab091703"),
    digest!("e8ce492160d067044b21672edc904611357a0b432dfbd20d6c5ddc541bed5502"),
    digest!("3c1bfe6196591048269c2f53f2ea9c3e3249543ffc0508711ea380745ec37826"),
    digest!("d446890b896fb956354215537b0ee846d1734f40bf44ca33d23f4b6f5940cc3f"),
    digest!("67c7dd2da611b96a644d3e19e2f1c44f929e461971389e30a0d4680717651908"),
    digest!("b108d025a73882560bdc69351dbaa45a24dcc658b431b265aecced185efd746d"),
    digest!("37158d6f1f9e090b140bc65f1b89774ac1cfba0943c6ad338c0b25535ed91136"),
    digest!("8761bc67f79f5751d48bfb50b280414172df2807e1c1af163d2d1277d4947e12"),
    digest!("876a30068ae29851e9f72f439f71a70bd9d2e058b473ac0c1d78896eff3c6c6e"),
    digest!("e6c4b0600f5a2519cea46902be244c27e55e4c3881d5da5dca177750b78a2461"),
];
pub const KECCAK_CONTROL_ROOTS: [Digest; 11] = [
    digest!("17cd462c927b0f4d1280ae4646b9890c2854b01d9f20bc3cfba258233a43ca63"),
    digest!("9c5fb251fadbc81c6b837e53be22347083c6591a80b9af1fa3ba565d2def4b34"),
    digest!("dcda7921ff0f475596b95e4d6363a10183ac5903c416a61a40206044c763e93e"),
    digest!("5108186a3f6cfd048acb580dc6d7976055a4fc5025ee4e5020d30e70e11b7324"),
    digest!("f9d6f54df5f4ae5c4f5d1767f93a316cbd74472dd573cd5ac8a0fd517970e433"),
    digest!("e520090c9a020819d05cec6cc546944d1b071d47b45e151aa1deaa446de8df0c"),
    digest!("5ac7c521ecebb50896d116246676cf60dc185a39e7577f00523cd91a33156143"),
    digest!("4dfe0e10d96bf85ed3885228115c3c19019de4468e5792680200727317e75339"),
    digest!("0556293167fe3b082223950bf70f651158297877d126e04d05fc6b03544c101a"),
    digest!("2890876063ef45775793b96920c85748d34ed04b1f5b041dc0529d73a3db384a"),
    digest!("b23fec31e8bd6100d3a9a7397d85cd3b409ebd5fdfea38594f0396536e8a2b47"),
];
